# Generated by Django 4.1.1 on 2025-11-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Price', models.IntegerField()),
                ('Brand', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Price', models.IntegerField()),
                ('Image', models.CharField(max_length=200)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField()),
                ('Status', models.CharField(max_length=20)),
                ('IBAN', models.CharField(max_length=34)),
                ('PaymentDate', models.DateField()),
                ('Method', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.item')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField()),
                ('Rating', models.IntegerField()),
                ('Comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackNumber', models.CharField(max_length=50)),
                ('Product', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('ProfilePicture', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='review',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='Shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.shipment'),
        ),
        migrations.AddField(
            model_name='order',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.user'),
        ),
        migrations.AddField(
            model_name='item',
            name='Reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.review'),
        ),
        migrations.AddField(
            model_name='item',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.type'),
        ),
    ]
