# Generated by Django 4.1.1 on 2025-11-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_atv_brand_item_order_review_shipment_status_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ATV',
        ),
        migrations.AddField(
            model_name='status',
            name='Type',
            field=models.CharField(default='Order', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.status'),
        ),
    ]
