# Generated by Django 5.2.8 on 2025-11-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_review_createdat_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.ImageField(upload_to='items/'),
        ),
    ]
